<a href="https://colab.research.google.com/github/veliaaf/big-data/blob/main/latihan02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**
---
Import Numpy dan mengecek versi dari package numpy tersebut dengan cara :


In [3]:
import numpy
numpy.__version__

'1.19.5'

In [4]:
import numpy as np

**Understanding Data Types in Python** 

---
Kode dalam python dilakukan seperti dibawah ini


In [11]:
result = 0
for i in range(100):
    result +=i

In [8]:
x=4
x="four"

**List pada Python**
---
yang pertama itu list pada integer

In [14]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
type(L[0])

int

yang kedua list dari string

In [15]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [17]:
type(L2[0])

str

yang ketiga, dapat menampilkan jenis list tersebut.

In [19]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

**Fixed Type Array in Python**

---
Tipe data array bawaan yaitu seperti di bawah ini:


In [20]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Creating Array from Python Lists

In [25]:
import numpy as np
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

Jika terdapat tipe data yang berbeda dalam satu list, maka akan disamakan semuanya seperti contoh di bawah ini disamakan ke tipe data float

In [23]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Jika kita ingin secara eksplisit mengatur tipe data dari larik yang dihasilkan, kita dapat menggunakan dtype dengan kata kunci:

In [24]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Tidak seperti daftar Python, array NumPy dapat secara eksplisit multidimensi; ini dia salah satu cara untuk menginisialisasi array multidimensi menggunakan list:

In [26]:
#nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

**Creating Array from Scratch**

---
Khusus untuk larik yang lebih besar, akan lebih efisien untuk membuat larik dari awal menggunakan rutinitas dibangun ke dalam NumPy. Berikut beberapa contohnya:


In [27]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
#Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [31]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.90849028, 0.35079912, 0.60876941],
       [0.01109576, 0.58999613, 0.42482657],
       [0.82106683, 0.37845371, 0.11786836]])

In [35]:
#Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.19875192,  1.74950937,  0.93461177],
       [-1.70629863,  0.1911192 ,  0.33910293],
       [ 0.30694457, -0.04683741,  1.27579969]])

In [36]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 9, 4],
       [0, 2, 0],
       [3, 0, 7]])

In [37]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

**Numpy Array Attributes**

---

Pertama mari kita bahas beberapa atribut array yang berguna. Kami akan mulai dengan mendefinisikan tiga secara acak array: array satu dimensi, dua dimensi, dan tiga dimensi. Kami akan menggunakan Generator nomor acak NumPy, yang akan kita seed dengan nilai yang ditetapkan untuk pastikan bahwa array acak yang sama dibuat setiap kali kode ini dijalankan:

In [44]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
print("X1 : ", x1)
print("X2 : ", x2)
print("x3 :", x3)

X1 :  [5 0 3 3 7 9]
X2 :  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3 : [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Setiap larik memiliki atribut ndim (jumlah dimensi), shape (bentuk masing-masing dimensi), dan size (ukuran total larik). Atribut lain termasuk ukuran item, yang mencantumkan ukuran (dalam byte) dari setiap elemen array,
dan nbytes, yang mencantumkan ukuran total (dalam byte) dari array:

In [47]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


**Array Indexing: Accessing Single Elements**

---
Jika Anda terbiasa dengan pengindeksan list standar Python, pengindeksan di NumPy akan terasa cukup familiar. Dalam larik satu dimensi, Anda dapat mengakses nilai ke-i (dihitung dari nol) dengan menentukan indeks yang diinginkan dalam tanda kurung siku, seperti dengan list Python:

In [48]:
x1

array([5, 0, 3, 3, 7, 9])

In [49]:
x1[0]

5

In [50]:
x1[4]

7

Untuk mengindeks dari akhir larik, Anda dapat menggunakan indeks negatif:

In [53]:
x1[-1]

9

Dalam larik multidimensi, Anda mengakses item menggunakan tupel yang dipisahkan koma dari
indeks:

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [55]:
x2[0, 0]

3

In [56]:
x2[2, -1]

7

Anda juga dapat mengubah nilai menggunakan salah satu notasi indeks di atas:

In [57]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

**Array Slicing: Accessing Subarrays**

---

Sama seperti kita dapat menggunakan tanda kurung siku untuk mengakses elemen array individu, kita juga dapat menggunakan
mereka untuk mengakses subarray dengan notasi irisan, ditandai dengan karakter titik dua (:).
Sintaks pemotongan NumPy mengikuti yang ada pada daftar Python standar; untuk mengakses sepotong
sebuah array x, gunakan ini:
x [mulai: berhenti: langkah]
Jika salah satu dari ini tidak ditentukan, nilai default-nya adalah start = 0, stop = size of
dimensi, langkah = 1. Kita akan melihat cara mengakses subarray dalam satu dimensi dan dalam
berbagai dimensi.

---
One-dimensional subarrays


In [58]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [60]:
x[4:7] # middle subarray

array([4, 5, 6])

In [61]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [62]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

Multidimensional subarrays

In [63]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [64]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [65]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [66]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

**Accressing Arrays rows and columns**

---
Salah satu rutinitas yang biasanya dibutuhkan adalah mengakses single
baris atau kolom dari sebuah larik. Anda dapat melakukan ini dengan menggabungkan pengindeksan dan pemotongan,
menggunakan irisan kosong yang ditandai dengan satu titik dua (:):


In [67]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [68]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


**Subarrays as no-copy views**

---
Satu hal penting — dan sangat berguna — untuk diketahui tentang irisan array adalah bahwa mereka
mengembalikan tampilan daripada salinan data larik. Ini adalah salah satu area di mana NumPy
mengiris array berbeda dari pemotongan daftar Python: dalam daftar, irisan akan menjadi salinan. Pertimbangkan kami
larik dua dimensi dari sebelumnya:


In [69]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Mari kita ekstrak subarray 2x2 dari ini:

In [70]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Sekarang jika kita memodifikasi sublarik ini, kita akan melihat bahwa larik asli berubah :

In [71]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [72]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


**Creating copies of arrays**

---
Terlepas dari fitur bagus dari tampilan array, terkadang berguna untuk sebaliknya secara eksplisit
salin data dalam array atau subarray. Ini dapat dilakukan paling mudah dengan file
copy () metode:


In [73]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


Jika sekarang kita memodifikasi subarray ini, maka akan berubah seperti berikut:

In [74]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [75]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


**Reshaping of Arrays**

---
Jenis operasi lain yang berguna adalah pembentukan kembali array. Cara paling fleksibel dari
melakukan ini dengan metode reshape (). Misalnya, jika Anda ingin memasukkan angka
1 hingga 9 dalam kisi 3 × 3, Anda dapat melakukan hal berikut:


In [76]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
x = np.array([1, 2, 3])
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [78]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [80]:
#column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [81]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

**Array Concatenation and Splitting**

---
Semua rutinitas sebelumnya bekerja pada array tunggal. Itu juga memungkinkan untuk digabungkan
beberapa array menjadi satu, dan sebaliknya membagi satu array menjadi beberapa array.
Kami akan melihat operasi tersebut di sini.

---
**Concatenation of arrays**

---

Penggabungan, atau penggabungan dua larik di NumPy, dilakukan terutama
melalui rutinitas np.concatenate, np.vstack, dan np.hstack. np.concatenate
mengambil tupel atau daftar larik sebagai argumen pertamanya, seperti yang bisa kita lihat di sini:



In [82]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [83]:
#Anda juga dapat menggabungkan lebih dari dua larik sekaligus:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [84]:
#np.concatenate juga dapat digunakan untuk array dua dimensi:
grid = np.array([[1, 2, 3],
[4, 5, 6]])

In [86]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [87]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Splitting of arrays**

---
Kebalikan dari penggabungan adalah pemisahan, yang diimplementasikan oleh fungsi
np.split, np.hsplit, dan np.vsplit. Untuk masing-masing ini, kita dapat memberikan daftar indeks
memberikan poin perpecahan:


In [88]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [89]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [91]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
